Repository RadekBucki/ConcurrentProgramming, pull requests merged in 2022-04, with the labels that each got.

#11 10 create architecture tree
  .github/workflows/dotnet.yml
  ConcurrentProgramming.sln
  Data/Data.csproj
  Data/HelloWorld.cs
  HelloWorldTests/UnitTest1.cs
  Logic/HelloWorld.cs
  Logic/Logic.csproj
  Model/HelloWorld.cs
  Model/Model.csproj
  Tests/DataTests/HelloWorld.cs
  Tests/LogicTests/HelloWorld.cs
  Tests/Tests.csproj
  View/App.xaml
  View/App.xaml.cs
  View/AssemblyInfo.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/View.csproj
  ViewModel/HelloWorld.cs
  ViewModel/ViewModel.csproj
Labels: task

#13 Creata Data and Logic for balls
  Data/Ball.cs
  Data/BallsRepository.cs
  Data/HelloWorld.cs
  Logic/BallsManager.cs
  Logic/HelloWorld.cs
  Model/HelloWorld.cs
  Tests/DataTests/BallTest.cs
  Tests/DataTests/BallsRepositoryTest.cs
  Tests/DataTests/HelloWorld.cs
  Tests/LogicTests/BallsManagerTest.cs
  Tests/LogicTests/HelloWorld.cs
Labels: task

#15 Refactor to avoid data repetition
  ViewModel/MainViewModel.cs
Labels: refactor

#14 Create size parameter
  Data/Ball.cs
  Logic/BallsManager.cs
  Model/MainModel.cs
  Tests/DataTests/BallTest.cs
  Tests/DataTests/BallsRepositoryTest.cs
  Tests/LogicTests/BallsManagerTest.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  ViewModel/MainViewModel.cs
Labels: bug, task
